---
- name: Enable Avocado-lts repository
  yum_repository:
    name: avocado-lts
    description: Long-term support release of Avocado testing framework
    baseurl: https://repos-avocadoproject.rhcloud.com/static/lts/fedora-24-noarch/
    gpgcheck: yes
    gpgkey: https://repos-avocadoproject.rhcloud.com/static/crosa_redhat_com.gpg
    enabled: yes
    state: present

- name: Install Avocado
  dnf: name=avocado state=latest

- name: Avocado test - Trivial
  raw: /usr/bin/avocado run /bin/true

- name: Copy example test
  copy:
    src: avocado_deployment/files/logtest.py
    dest: /tmp/logtest.py

- name: Avocado test - Upstream logging example
  raw: /usr/bin/avocado --show progress run /tmp/logtest.py
  register: logtest

- name: Display upstream logging test output
  debug: var=logtest.stdout_lines
